import {body,context,db,failure,identity,HttpError} from '@/lib/server';
export const dynamic='force-dynamic';
export async function POST(req:Request){try{const user=await identity(req),v=await body(req);if(typeof v.name!=='string'||!v.name.trim()||v.name.length>120)throw new HttpError(400,'Name is required');if(typeof v.business_name!=='string'||!v.business_name.trim()||v.business_name.length>120)throw new HttpError(400,'Business name is required');const result=await db().begin(async sql=>{await sql`select pg_advisory_xact_lock(hashtext(${user.id}))`;const exists=await sql`select id from organization_members where user_id=${user.id}`;if(exists.length)throw new HttpError(409,'You already belong to a workspace');await sql`insert into users(id,name) values(${user.id},${v.name.trim()}) on conflict(id) do update set name=excluded.name`;const [org]=await sql`insert into organizations(name) values(${v.business_name.trim()}) returning id`;await sql`insert into organization_members(organization_id,user_id,role) values(${org.id},${user.id},'owner')`;return org});return Response.json(result)}catch(e){return failure(e)}}
export async function GET(req:Request){try{const c=await context(req),sql=db(),url=new URL(req.url);const limit=Math.min(1000,Math.max(50,Number(url.searchParams.get('limit'))||100));const conversation=url.searchParams.get('conversation');const before=url.searchParams.get('before');if(conversation){const messages=await sql`select m.*,(select e.error_code from message_status_events e where e.organization_id=m.organization_id and e.meta_message_id=m.meta_message_id and e.status='failed' order by e.event_at desc limit 1) meta_error_code from messages m where m.organization_id=${c.org} and m.conversation_id=${conversation} and (${before}::timestamptz is null or m.created_at<${before}::timestamptz) order by m.created_at desc,m.id desc limit 50`;return Response.json({messages:messages.reverse()})}
const [org]=await sql`select * from organizations where id=${c.org}`;
const whatsappAccounts=await sql`select id,label,display_phone_number,verified_name,phone_number_id,business_account_id,is_active,is_default,created_at,updated_at from whatsapp_accounts where organization_id=${c.org} order by is_default desc,created_at`;
const [contacts,conversations,messages,members,...rest]=await Promise.all([sql`select c.*,coalesce((select jsonb_agg(t.name order by t.name) from contact_tags ct join tags t on t.id=ct.tag_id where ct.contact_id=c.id),'[]') tags from contacts c where organization_id=${c.org} order by name limit ${limit}`,sql`select * from conversations where organization_id=${c.org} order by updated_at desc limit ${limit}`,sql`select m.*,(select e.error_code from message_status_events e where e.organization_id=m.organization_id and e.meta_message_id=m.meta_message_id and e.status='failed' order by e.event_at desc limit 1) meta_error_code from (select * from messages where organization_id=${c.org} order by created_at desc limit ${limit*5}) m order by m.created_at`,sql`select u.id,u.name,m.role,m.status from organization_members m join users u on u.id=m.user_id where organization_id=${c.org}`, ...['notes','templates','quick_replies','products','campaigns','campaign_recipients','automation_rules','audit_logs','notifications'].map(table=>sql`select * from ${sql(table)} where organization_id=${c.org} order by created_at desc limit ${limit}`)]);
const [notes,templates,quick_replies,products,campaigns,campaign_recipients,automation_rules,audit_logs,notifications]=rest;
const [analytics]=await sql`select (select count(*) from messages where organization_id=${c.org} and direction='out') sent,(select count(*) from messages where organization_id=${c.org} and direction='in') received,(select count(*) from conversations where organization_id=${c.org}) conversations,(select count(*) from conversations where organization_id=${c.org} and mode='ai') ai,(select count(*) from conversations where organization_id=${c.org} and mode='human') human,(select count(*) from messages where organization_id=${c.org} and status in('delivered','read')) delivered,(select count(*) from messages where organization_id=${c.org} and status='read') read,(select count(*) from audit_logs where organization_id=${c.org} and body='Conversation changed to human') handovers`;
return Response.json({organization_id:c.org,user_id:c.user,role:c.role,contacts,conversations,messages,members,notes,templates,quick_replies,products,campaigns,campaign_recipients,automation_rules,audit_logs,notifications,analytics,settings:{...org.settings,name:org.name},connection:{whatsapp:whatsappAccounts.some(account=>account.is_active),ai:!!process.env.AI_API_KEY,whatsapp_accounts:whatsappAccounts},has_more:contacts.length===limit||conversations.length===limit},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
