import {describe,it,expect} from 'vitest';
import {catalogueDemoProducts,catalogueGroups,formatPrice,meaningfulPrice,productSnapshot,type Filters} from '../lib/catalogue';
import {demoData,demoAction} from '../lib/demo';
const all:Filters={query:'',category:'',brand:'',form:'',stock:'',sort:'name',featured:false};
describe('Catalogue browsing and chat sharing',()=>{
it('groups each horizontal rail into exactly one category',()=>{const groups=catalogueGroups(catalogueDemoProducts(),all);expect(groups.map(x=>x.category)).toEqual(['Injection','Tablet','Ointment','Surgical','General / Consumables']);for(const group of groups)expect(group.products.every(p=>p.category===group.category)).toBe(true);expect(groups[0].products.length).toBeGreaterThan(3)});
it('searches composition and brand, and combines all filters',()=>{const products=[{id:'1',name:'Item',brand:'Example',composition:'Compound',category:'Tablet',form_type:'Tablet',stock:2},{id:'2',name:'Other',brand:'Other',composition:'Compound',category:'Tablet',form_type:'Tablet',stock:0}];expect(catalogueGroups(products,{...all,query:'compound',brand:'Example',stock:'in_stock',form:'Tablet',category:'Tablet'})[0].products.map(p=>p.id)).toEqual(['1']);expect(catalogueGroups(products,{...all,query:'missing'})).toEqual([])});
it('handles missing metadata and never renders an unsafe image URL',()=>{const s=productSnapshot({id:'x',name:'Legacy',stock:0,image_url:'javascript:alert(1)'});expect(s.image_url).toBe('');expect(s.category).toBe('General / Consumables');expect(s.availability).toBe('out_of_stock')});
it('keeps on-request availability distinct from zero stock',()=>expect(productSnapshot({id:'x',stock:0,availability:'on_request'}).availability).toBe('on_request'));
it('shares multiple product cards and preserves immutable snapshots',()=>{let d=demoData();const ids=d.products.slice(0,3).map(p=>p.id);for(const id of ids)d=demoAction(d,{type:'send',id:'v0',values:{kind:'product',product_id:id}});const sent=d.messages.filter(m=>m.kind==='product');expect(sent).toHaveLength(3);expect(sent.every(m=>m.status==='demo'&&m.product_snapshot.name)).toBe(true);const old=sent[0].product_snapshot.name;d.products[0].name='Renamed';expect(sent[0].product_snapshot.name).toBe(old);expect(d.conversations[0].mode).toBe('human')});
it('prevents sharing nonexistent products and closed-window sends',()=>{expect(()=>demoAction(demoData(),{type:'send',id:'v0',values:{kind:'product',product_id:'missing'}})).toThrow('Product not found');expect(()=>demoAction(demoData(),{type:'send',id:'v4',values:{kind:'product',product_id:'catalogue-demo-0'}})).toThrow('window')});
it('supports featured filtering',()=>expect(catalogueGroups(catalogueDemoProducts(),{...all,featured:true}).flatMap(x=>x.products).every(p=>p.featured)).toBe(true));
it('omits empty and zero prices instead of rendering a fake amount',()=>{expect(meaningfulPrice(null)).toBeNull();expect(meaningfulPrice('')).toBeNull();expect(meaningfulPrice(0)).toBeNull();expect(formatPrice({...productSnapshot({id:'p',name:'Item'}),price:null})).toBe('');expect(formatPrice({...productSnapshot({id:'p',name:'Item'}),price:120})).toContain('120')});
});
