import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import {beforeAll,afterAll,describe,it,expect} from 'vitest';
let db:PGlite;
const org1='10000000-0000-4000-8000-000000000001',org2='10000000-0000-4000-8000-000000000002',u1='20000000-0000-4000-8000-000000000001',u2='20000000-0000-4000-8000-000000000002';
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);`);for(const file of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')))await db.exec(readFileSync('supabase/migrations/'+file,'utf8'));await db.exec(`insert into auth.users(id) values('${u1}'),('${u2}');insert into users(id,name) values('${u1}','One'),('${u2}','Two');insert into organizations(id,name) values('${org1}','One'),('${org2}','Two');insert into organization_members(organization_id,user_id,role) values('${org1}','${u1}','owner'),('${org2}','${u2}','agent');insert into contacts(organization_id,name,phone) values('${org1}','Visible','+919000000001'),('${org2}','Hidden','+919000000002');`)});
afterAll(async()=>{await db.close()});
describe('PostgreSQL migration and tenant isolation',()=>{
it('enables RLS on every public table',async()=>{const result=await db.query(`select tablename from pg_tables where schemaname='public' and rowsecurity=false`);expect(result.rows).toEqual([])});
it('restricts authenticated reads to membership',async()=>{await db.exec(`set role authenticated;set request.jwt.claim.sub='${u1}'`);const result=await db.query<{name:string}>('select name from contacts');expect(result.rows.map(x=>x.name)).toEqual(['Visible']);await db.exec('reset role')});
it('blocks direct client writes even for an owner',async()=>{await db.exec(`set role authenticated;set request.jwt.claim.sub='${u1}'`);await expect(db.exec(`update contacts set organization_id='${org2}'`)).rejects.toThrow(/permission denied/);await db.exec('reset role')});
it('does not expose data to anonymous clients',async()=>{await db.exec('set role anon');await expect(db.query('select * from messages')).rejects.toThrow(/permission denied/);await db.exec('reset role')});
it('rejects cross-tenant foreign keys even for a privileged server connection',async()=>{const r=await db.query<{id:string}>(`select id from contacts where organization_id='${org2}'`);await expect(db.exec(`insert into conversations(organization_id,contact_id) values('${org1}','${r.rows[0].id}')`)).rejects.toThrow(/foreign key/)});
it('deduplicates inbound messages and status events',async()=>{const r=await db.query<{id:string}>(`insert into conversations(organization_id,contact_id) select organization_id,id from contacts where organization_id='${org1}' returning id`);const v=r.rows[0].id;await db.exec(`insert into messages(organization_id,conversation_id,direction,meta_message_id) values('${org1}','${v}','in','wamid.test')`);await expect(db.exec(`insert into messages(organization_id,conversation_id,direction,meta_message_id) values('${org1}','${v}','in','wamid.test')`)).rejects.toThrow(/unique/)});
it('keeps the media bucket private',async()=>{const r=await db.query<{public:boolean}>('select public from storage.buckets');expect(r.rows[0].public).toBe(false)});
});
