import {productSnapshot} from '@/lib/catalogue';
import {z} from 'zod';
import {body,context,db,failure,HttpError} from '@/lib/server';
import {canAdmin,canManage,messagingOpen,normalizePhone,templateText,templateVariables} from '@/lib/domain';
import {syncTemplates,type WhatsAppAccount} from '@/services/whatsapp.service';
const text=z.string().trim().min(1).max(4000),idSchema=z.string().uuid();
export async function POST(req:Request){try{const c=await context(req),a=z.object({type:z.string(),id:idSchema.optional(),values:z.record(z.string(),z.any()).default({})}).parse(await body(req)),v=a.values;
if(['campaign','campaign_start','product','automation','sync_templates'].includes(a.type)&&!canManage(c.role))throw new HttpError(403,'Manager access required');if(['settings','member'].includes(a.type)&&!canAdmin(c.role))throw new HttpError(403,'Admin access required');
if(a.type==='sync_templates'){const requested=v.whatsapp_account_id?idSchema.parse(v.whatsapp_account_id):null;const [account]=requested?await db()`select * from whatsapp_accounts where id=${requested} and organization_id=${c.org} and is_active=true`:await db()`select * from whatsapp_accounts where organization_id=${c.org} and is_active=true order by is_default desc,created_at limit 1`;if(!account)throw new HttpError(409,'Connect this workspace to WhatsApp first');const templates=await syncTemplates(account as WhatsAppAccount);await db().begin(async sql=>{for(const t of templates){await sql`insert into templates(organization_id,whatsapp_account_id,meta_id,name,category,language,status,body,components) values(${c.org},${account.id},${t.id},${t.name},${t.category},${t.language},${t.status},${t.components?.find((x:any)=>x.type==='BODY')?.text||''},${sql.json(t.components||[])}) on conflict(organization_id,whatsapp_account_id,name,language) where whatsapp_account_id is not null do update set meta_id=excluded.meta_id,status=excluded.status,body=excluded.body,components=excluded.components,updated_at=now()`;}});return Response.json({ok:true})}
await db().begin(async sql=>{
let conv:any;
if(['mode','read','assign','send','note','clear_chat'].includes(a.type)){idSchema.parse(a.id);await sql`select pg_advisory_xact_lock(hashtext(${a.id!}))`;[conv]=await sql`select * from conversations where id=${a.id!} and organization_id=${c.org} for update`;if(!conv)throw new HttpError(404,'Conversation not found');}
const log=async(message:string)=>sql`insert into audit_logs(organization_id,conversation_id,actor_id,body) values(${c.org},${conv?.id||null},${c.user},${message})`;
const pause=async(mode:string)=>{await sql`update conversations set mode=${mode},version=version+1,assigned_to=case when ${mode}='human' then ${c.user}::uuid else assigned_to end,updated_at=now() where id=${conv.id} and organization_id=${c.org}`;await sql`update ai_sessions set status='cancelled' where conversation_id=${conv.id} and organization_id=${c.org} and status in('queued','generating')`;await sql`update messages set status='cancelled' where conversation_id=${conv.id} and organization_id=${c.org} and sender_name='Open Chet AI' and status='queued'`;};
switch(a.type){
case 'mode':{const mode=z.enum(['ai','paused','human']).parse(v.mode);await pause(mode);await log(`Conversation changed to ${mode}`);break;}
case 'read':await sql`update conversations set unread=0 where id=${conv.id} and organization_id=${c.org}`;break;
case 'assign':{const user=z.string().uuid().nullable().parse(v.assigned_to);if(user){const member=await sql`select id from organization_members where organization_id=${c.org} and user_id=${user}`;if(!member.length)throw new HttpError(400,'Agent is not in this workspace')};await sql`update conversations set assigned_to=${user} where id=${conv.id} and organization_id=${c.org}`;await sql`insert into conversation_assignments(organization_id,conversation_id,user_id,assigned_by) values(${c.org},${conv.id},${user},${c.user})`;await sql`insert into notifications(organization_id,conversation_id,body) values(${c.org},${conv.id},'Conversation assigned')`;break;}
case 'send':{const [connection]=await sql`select id from whatsapp_accounts where id=${conv.whatsapp_account_id} and organization_id=${c.org} and is_active=true and access_token_ciphertext is not null`;if(!connection)throw new HttpError(409,'Connect this conversation to an active WhatsApp number before sending');const key=idSchema.parse(v.idempotency_key);if((await sql`select id from messages where organization_id=${c.org} and idempotency_key=${key}`).length)break;const kind=z.enum(['text','template','image','document','video','audio','product']).parse(v.kind||'text');let snapshot:any=null;let payload:any,display=String(v.body||'');
if(kind==='template'){const [t]=await sql`select * from templates where organization_id=${c.org} and id=${idSchema.parse(v.template_id)} and status='APPROVED' and (whatsapp_account_id=${conv.whatsapp_account_id} or whatsapp_account_id is null)`;if(!t)throw new HttpError(400,'Choose an approved template for this WhatsApp number');const variables=z.array(z.string().max(1000)).parse(v.variables||[]);if(templateVariables(t.body).length!==variables.length)throw new HttpError(400,'Fill every template variable');if(t.components.some((x:any)=>!['BODY','FOOTER'].includes(x.type)))throw new HttpError(400,'This template needs unsupported header or button parameters');display=templateText(t.body,variables);payload={type:'template',template:{name:t.name,language:{code:t.language},components:variables.length?[{type:'body',parameters:variables.map(t=>({type:'text',text:t}))}]:[]}};
}else{if(!messagingOpen(conv.last_inbound_at?.toISOString()))throw new HttpError(409,'Template required: the 24-hour messaging window has closed');if(kind==='text'){display=text.parse(v.body);payload={type:'text',text:{body:display}}}else if(kind==='product'){const [p]=await sql`select * from products where id=${idSchema.parse(v.product_id)} and organization_id=${c.org}`;if(!p?.catalogue_id||!p?.retailer_id)throw new HttpError(400,'Add Meta catalogue and retailer identifiers first');payload={type:'interactive',interactive:{type:'product',body:{text:p.name},action:{catalog_id:p.catalogue_id,product_retailer_id:p.retailer_id}}};display=p.name;snapshot=productSnapshot({...p,id:String(p.id)});}else{const mediaId=text.parse(v.media_id);payload={type:kind,[kind]:{id:mediaId,...(kind==='document'?{filename:display}:{}),...(['image','video'].includes(kind)&&display?{caption:display}:{})}}}}
await pause('human');await sql`insert into messages(organization_id,conversation_id,direction,kind,body,sender_id,sender_name,payload,idempotency_key,media_id,product_snapshot) values(${c.org},${conv.id},'out',${kind},${display},${c.user},${c.name},${sql.json(payload)},${key},${v.media_id||null},${snapshot?sql.json(snapshot):null})`;await sql`update conversations set preview=${display},updated_at=now() where id=${conv.id} and organization_id=${c.org}`;break;}
case 'note':await sql`insert into notes(organization_id,conversation_id,body,author_id,author_name) values(${c.org},${conv.id},${text.parse(v.body)},${c.user},${c.name})`;break;
case 'clear_chat':await sql`delete from notes where organization_id=${c.org} and conversation_id=${conv.id}`;await sql`delete from messages where organization_id=${c.org} and conversation_id=${conv.id}`;await sql`update conversations set preview='',unread=0,updated_at=now() where organization_id=${c.org} and id=${conv.id}`;await log('Conversation history cleared');break;
case 'contact':{const contact=z.object({name:z.string().trim().min(1).max(120),phone:z.string().transform(normalizePhone),company:z.string().max(200).default(''),category:z.string().max(100).default(''),priority:z.enum(['normal','high']).default('normal'),opted_in:z.boolean().default(false),custom_fields:z.record(z.string(),z.string()).default({}),tags:z.array(z.string().trim().min(1).max(50)).max(30).default([])}).parse(v);const {tags,...fields}=contact;const write={...fields,custom_fields:sql.json(fields.custom_fields)};let contactId=a.id;if(a.id){const updated=await sql`update contacts set ${sql(write)},updated_at=now() where id=${a.id} and organization_id=${c.org} returning id`;if(!updated.length)throw new HttpError(404,'Contact not found');}else{const [row]=await sql`insert into contacts ${sql({...write,organization_id:c.org})} returning id`;contactId=row.id}await sql`delete from contact_tags where contact_id=${contactId!} and organization_id=${c.org}`;for(const name of new Set(tags)){const [tag]=await sql`insert into tags(organization_id,name) values(${c.org},${name}) on conflict(organization_id,name) do update set name=excluded.name returning id`;await sql`insert into contact_tags(organization_id,contact_id,tag_id) values(${c.org},${contactId!},${tag.id})`;}await log('Contact saved');break;}
case 'open':{const id=idSchema.parse(a.id);if(!(await sql`select id from contacts where organization_id=${c.org} and id=${id}`).length)throw new HttpError(404,'Contact not found');const [account]=await sql`select id from whatsapp_accounts where organization_id=${c.org} and is_active=true order by is_default desc,created_at limit 1`;if(!account)throw new HttpError(409,'Connect a WhatsApp number before starting a conversation');await sql`insert into conversations(organization_id,whatsapp_account_id,contact_id) values(${c.org},${account.id},${id}) on conflict(organization_id,whatsapp_account_id,contact_id) where whatsapp_account_id is not null do nothing`;break;}
case 'settings':{const settings=z.object({name:z.string().min(1).max(120),ai_enabled:z.boolean(),auto_pause:z.boolean(),tone:z.enum(['Professional','Friendly','Concise']),instructions:z.string().max(8000),blocked_topics:z.string().max(2000),business_hours:z.string().max(100),timezone:z.string().max(80),escalation_threshold:z.coerce.number().min(0).max(1)}).parse(v);const {name,...rest}=settings;await sql`update organizations set name=${name},settings=${sql.json(rest)} where id=${c.org}`;await log('Workspace settings updated');break;}
case 'member':{const target=idSchema.parse(v.user_id),role=z.enum(['admin','manager','agent']).parse(v.role);if(c.role!=='owner'&&role==='admin')throw new HttpError(403,'Only owners may grant admin access');if(!(await sql`select id from users where id=${target}`).length){const [authUser]=await sql`select id,email from auth.users where id=${target}`;if(!authUser)throw new HttpError(400,'Ask the teammate to sign up first');await sql`insert into users(id,name) values(${target},${z.string().max(120).parse(v.name)})`;}const [existing]=await sql`select role from organization_members where organization_id=${c.org} and user_id=${target}`;if(existing?.role==='owner')throw new HttpError(403,'Owner role cannot be changed here');if(existing?.role==='admin'&&c.role!=='owner')throw new HttpError(403,'Only owners can change administrators');await sql`insert into organization_members(organization_id,user_id,role) values(${c.org},${target},${role}) on conflict(organization_id,user_id) do update set role=excluded.role`;await log('Team membership updated');break;}
case 'quick_reply':case 'product':case 'automation':{const tables={quick_reply:'quick_replies',product:'products',automation:'automation_rules'};let fields:any;if(a.type==='quick_reply')fields=z.object({shortcut:z.string().regex(/^\/[a-z0-9_-]{1,40}$/),body:text}).parse(v);if(a.type==='product')fields=z.object({brand:z.string().max(200).default(''),composition:z.string().max(500).default(''),strength:z.string().max(100).default(''),form_type:z.string().max(100).default(''),pack_size:z.string().max(100).default(''),notes:z.string().max(3000).default(''),featured:z.boolean().default(false),availability:z.enum(['in_stock','out_of_stock','on_request']).default('in_stock'),name:text,description:z.string().max(3000).default(''),category:z.string().max(100).default(''),price:z.union([z.coerce.number().positive(),z.null()]).optional().transform(value=>value??null),stock:z.coerce.number().int().min(0),currency:z.string().length(3).default('INR'),retailer_id:z.string().max(200).default(''),catalogue_id:z.string().max(200).default(''),image_url:z.string().refine(x=>!x||x.startsWith('https://')).default('')}).parse(v);if(a.type==='automation')fields=z.object({name:text,trigger:z.enum(['keyword','new_contact','tag']),match:z.string().max(200),action:z.enum(['pause','tag','assign','reply']),value:z.string().max(4000),enabled:z.boolean()}).parse(v);if(a.id)await sql`update ${sql(tables[a.type])} set ${sql(fields)} where organization_id=${c.org} and id=${a.id}`;else await sql`insert into ${sql(tables[a.type])} ${sql({...fields,organization_id:c.org})}`;break;}
case 'campaign':{const data=z.object({name:z.string().min(1).max(120),template_id:idSchema,tag:z.string().max(80).default(''),contact_ids:z.array(idSchema).max(1000).default([]),variables:z.array(z.string().max(1000)).default([]),scheduled_at:z.string().datetime().nullable().default(null)}).parse(v);const [t]=await sql`select * from templates where organization_id=${c.org} and id=${data.template_id} and status='APPROVED'`;if(!t)throw new HttpError(400,'An approved template is required');if(templateVariables(t.body).length!==data.variables.length)throw new HttpError(400,'Fill all template variables');await sql`insert into campaigns ${sql({...data,organization_id:c.org,contact_ids:sql.json(data.contact_ids),variables:sql.json(data.variables)})}`;break;}
case 'campaign_start':{const [campaign]=await sql`select c.*,t.whatsapp_account_id from campaigns c join templates t on t.id=c.template_id and t.organization_id=c.organization_id where c.id=${idSchema.parse(a.id)} and c.organization_id=${c.org} for update of c`;if(!campaign||campaign.status!=='draft')throw new HttpError(409,'Campaign already started or missing');const [account]=campaign.whatsapp_account_id?await sql`select id from whatsapp_accounts where id=${campaign.whatsapp_account_id} and organization_id=${c.org} and is_active=true`:await sql`select id from whatsapp_accounts where organization_id=${c.org} and is_active=true order by is_default desc,created_at limit 1`;if(!account)throw new HttpError(409,'WhatsApp is not connected');await sql`update campaigns set status='scheduled',scheduled_at=coalesce(scheduled_at,now()) where id=${campaign.id} and organization_id=${c.org}`;await log('Campaign scheduled');break;}
case 'notify_read':await sql`delete from notifications where organization_id=${c.org}`;break;
default:throw new HttpError(400,'Unknown action');}
});return Response.json({ok:true})}catch(e){return failure(e)}}
