import {db,failure} from '@/lib/server';
import {verifySignature} from '@/services/whatsapp.service';
import {statusAdvance} from '@/lib/domain';
export const runtime='nodejs';
export async function GET(req:Request){const p=new URL(req.url).searchParams;if(process.env.WHATSAPP_VERIFY_TOKEN&&p.get('hub.mode')==='subscribe'&&p.get('hub.verify_token')===process.env.WHATSAPP_VERIFY_TOKEN)return new Response(p.get('hub.challenge'));return new Response('Forbidden',{status:403})}
export async function POST(req:Request){const raw=await req.text();if(raw.length>2_000_000)return new Response('Too large',{status:413});if(!verifySignature(raw,req.headers.get('x-hub-signature-256'),process.env.META_APP_SECRET||''))return new Response('Invalid signature',{status:401});try{const payload=JSON.parse(raw);if(payload.object!=='whatsapp_business_account')return Response.json({ok:true});for(const entry of payload.entry||[])for(const change of entry.changes||[]){const value=change.value,org=process.env.WHATSAPP_ORGANIZATION_ID;if(!org)throw Error('Missing organization mapping');if(value.metadata?.phone_number_id!==process.env.WHATSAPP_PHONE_NUMBER_ID){if(change.field==='message_template_status_update'&&entry.id===process.env.WHATSAPP_BUSINESS_ACCOUNT_ID)await db()`update templates set status=${value.event},updated_at=now() where organization_id=${org} and meta_id=${String(value.message_template_id)}`;continue;}
for(const m of value.messages||[])await db().begin(async sql=>{await sql`select pg_advisory_xact_lock(hashtext(${m.id}))`;if((await sql`select id from messages where meta_message_id=${m.id}`).length)return;const phone=`+${m.from}`;const name=value.contacts?.find((x:any)=>x.wa_id===m.from)?.profile?.name||phone;const existing=await sql`select id from contacts where organization_id=${org} and phone=${phone}`;const [contact]=await sql`insert into contacts(organization_id,name,phone,source) values(${org},${name},${phone},'whatsapp') on conflict(organization_id,phone) do update set updated_at=now() returning *`;const [settings]=await sql`select settings from organizations where id=${org}`;const [conv]=await sql`insert into conversations(organization_id,contact_id,mode) values(${org},${contact.id},${settings.settings.ai_enabled?'ai':'paused'}) on conflict(organization_id,contact_id) do update set updated_at=now() returning *`;await sql`select pg_advisory_xact_lock(hashtext(${conv.id}))`;const timestamp=new Date(Number(m.timestamp)*1000);const kind=m.type||'unsupported',content=kind==='text'?m.text?.body:kind==='button'?m.button?.text:kind==='interactive'?(m.interactive?.button_reply?.title||m.interactive?.list_reply?.title):m[kind]?.caption||m[kind]?.filename||`[${kind}]`;
const [message]=await sql`insert into messages(organization_id,conversation_id,direction,kind,body,status,sender_name,meta_message_id,media_id,created_at) values(${org},${conv.id},'in',${kind},${content||''},'received',${name},${m.id},${m[kind]?.id||null},${timestamp}) returning id`;
await sql`update conversations set unread=unread+1,last_inbound_at=greatest(last_inbound_at,${timestamp}),preview=case when last_inbound_at is null or last_inbound_at<=${timestamp} then ${content||''} else preview end,updated_at=greatest(updated_at,${timestamp}),version=version+1 where id=${conv.id} and organization_id=${org}`;
// Invalidate older generated replies as soon as a newer message arrives.
await sql`update ai_sessions set status='cancelled' where organization_id=${org} and conversation_id=${conv.id} and status in('queued','generating')`;await sql`update messages set status='cancelled' where organization_id=${org} and conversation_id=${conv.id} and sender_name='Open Chet AI' and status='queued'`;
const rules=await sql`select * from automation_rules where organization_id=${org} and enabled=true order by created_at`;
let replied=false;for(const rule of rules){const matches=rule.trigger==='new_contact'?!existing.length:rule.trigger==='keyword'?String(content).toLowerCase().includes(rule.match.toLowerCase()):(await sql`select 1 from contact_tags ct join tags t on t.id=ct.tag_id where ct.contact_id=${contact.id} and t.name=${rule.match} and ct.organization_id=${org}`).length>0;if(!matches)continue;
if(rule.action==='pause')await sql`update conversations set mode='paused',version=version+1 where id=${conv.id} and organization_id=${org}`;
if(rule.action==='tag'){const [t]=await sql`insert into tags(organization_id,name) values(${org},${rule.value}) on conflict(organization_id,name) do update set name=excluded.name returning id`;await sql`insert into contact_tags(organization_id,contact_id,tag_id) values(${org},${contact.id},${t.id}) on conflict do nothing`;}
if(rule.action==='assign'&&/^[0-9a-f-]{36}$/i.test(rule.value)&&(await sql`select 1 from organization_members where organization_id=${org} and user_id=${rule.value}`).length)await sql`update conversations set assigned_to=${rule.value} where id=${conv.id} and organization_id=${org}`;
if(rule.action==='reply'&&conv.mode==='ai'&&settings.settings.ai_enabled&&!replied){await sql`insert into messages(organization_id,conversation_id,direction,body,sender_name,payload) values(${org},${conv.id},'out',${rule.value},'Open Chet AI',${sql.json({type:'text',text:{body:rule.value},expected_version:conv.version+1})})`;replied=true;}}
const [fresh]=await sql`select * from conversations where id=${conv.id} and organization_id=${org}`;
if(fresh.mode==='ai'&&settings.settings.ai_enabled&&!replied)await sql`insert into ai_sessions(organization_id,conversation_id,input_message_id,expected_version) values(${org},${conv.id},${message.id},${fresh.version})`;
await sql`insert into notifications(organization_id,conversation_id,body) values(${org},${conv.id},${`New message from ${name}`})`;
});
for(const s of value.statuses||[])await db().begin(async sql=>{await sql`insert into message_status_events(organization_id,meta_message_id,status,event_at,error_code) values(${org},${s.id},${s.status},${new Date(Number(s.timestamp)*1000)},${s.errors?.[0]?.code?.toString()||null}) on conflict do nothing`;const [m]=await sql`select id,status from messages where meta_message_id=${s.id} and organization_id=${org} for update`;if(m){const status=statusAdvance(m.status,s.status);await sql`update messages set status=${status},updated_at=now() where id=${m.id} and organization_id=${org}`;await sql`update campaign_recipients set status=${status} where message_id=${m.id} and organization_id=${org}`;if(status==='failed')await sql`insert into notifications(organization_id,body) values(${org},'A WhatsApp message failed. Open the inbox to review.')`;}});
}return Response.json({ok:true})}catch(e){return failure(e)}}
