'use client';
import {useRef,useState} from 'react';
import {Search,Package,ChevronLeft,ChevronRight,Send,X} from 'lucide-react';
import Dialog from './dialog';
import type {Row} from '@/lib/types';
import {availabilityLabel,catalogueGroups,productSnapshot,type Filters,type ProductSnapshot} from '@/lib/catalogue';

export function ProductImage({product}:{product:ProductSnapshot}){const [failed,setFailed]=useState(false);return <div className="catalogue-image">{product.image_url&&!failed?<img src={product.image_url} alt={product.name} loading="lazy" onError={()=>setFailed(true)}/>:<div className="catalogue-image-empty"><Package size={26} strokeWidth={1.4}/></div>}</div>}

function Price({product}:{product:ProductSnapshot}){if(!product.price)return null;return <strong className="catalogue-price">{product.currency==='INR'?'₹':`${product.currency} `}{product.price.toLocaleString('en-IN')}</strong>}

export function ProductMessage({product}:{product:ProductSnapshot}){return <article className="shared-product"><ProductImage product={product}/><div><small>{product.category}</small><h3>{product.name}</h3><p>{[product.brand,product.composition,product.strength].filter(Boolean).join(' · ')||product.form_type}</p><span className={`stock-badge ${product.availability}`}>{availabilityLabel(product.availability)}</span><Price product={product}/></div></article>}

function chunks<T>(items:T[],size:number){const result:T[][]=[];for(let i=0;i<items.length;i+=size)result.push(items.slice(i,i+size));return result;}

function ProductRail({category,products,onDetails}:{category:string;products:Row[];onDetails:(p:Row)=>void}){const rail=useRef<HTMLDivElement>(null),pages=chunks(products,6);const move=(direction:number)=>rail.current?.scrollBy({left:direction*rail.current.clientWidth,behavior:'smooth'});return <section className="catalogue-category" aria-label={category}><header><div><h3>{category}</h3><span>{products.length} products</span></div>{pages.length>1&&<div className="rail-buttons"><button type="button" aria-label={`Previous ${category} products`} onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button type="button" aria-label={`More ${category} products`} onClick={()=>move(1)}><ChevronRight size={18}/></button></div>}</header><div className="product-pages" ref={rail} tabIndex={0} aria-label={`${category} products`}>{pages.map((page,pageIndex)=><div className="product-page" key={`${category}-${pageIndex}`}>{page.map(p=>{const s=productSnapshot(p);return <article className="catalogue-product compact" key={p.id} onClick={()=>onDetails(p)}><ProductImage product={s}/><div className="catalogue-product-copy"><span className={`stock-dot ${s.availability}`} aria-label={availabilityLabel(s.availability)}/><h4>{s.name}</h4><p>{[s.brand,s.strength].filter(Boolean).join(' · ')||s.form_type||s.category}</p><div className="catalogue-card-bottom"><Price product={s}/><button type="button" className="product-details-button" onClick={e=>{e.stopPropagation();onDetails(p)}}>Details</button></div></div></article>})}</div>)}</div></section>}

export default function CataloguePanel({products,conversationName,onClose,onSend,canSend,demo}:{products:Row[];conversationName:string;onClose:()=>void;onSend:(ids:string[])=>Promise<string[]>;canSend:boolean;demo:boolean}){const [filters,setFilters]=useState<Filters>({query:'',category:'',brand:'',form:'',stock:'',sort:'name',featured:false}),[details,setDetails]=useState<Row|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState('');const groups=catalogueGroups(products,filters),categories=[...new Set(products.map(p=>productSnapshot(p).category))].sort();const update=(key:keyof Filters,value:string|boolean)=>setFilters(f=>({...f,[key]:value}));async function send(id:string){if(busy||!canSend)return;setBusy(true);setStatus('');try{const sent=await onSend([id]);if(sent.length){setStatus(demo?'Added to demo chat.':'Queued for sending.');setDetails(null)}else setStatus('Product could not be sent.');}catch{setStatus('Product could not be sent.')}finally{setBusy(false)}}
return <Dialog title="Catalogue" onClose={()=>{if(!busy)onClose()}}><div className="catalogue-experience catalogue-v2"><div className="catalogue-context"><span>Share with <strong>{conversationName}</strong></span><span>{demo?'Demo catalogue':'Business catalogue'}</span></div>{!canSend&&<div className="notice">The messaging window is closed. Wait for a reply or use an approved template before sharing a product.</div>}<div className="catalogue-sticky compact"><div className="catalogue-search"><Search size={18}/><input aria-label="Search catalogue" placeholder="Search medicine, brand or composition…" value={filters.query} onChange={e=>update('query',e.target.value)}/></div><div className="catalogue-category-chips"><button className={!filters.category?'active':''} onClick={()=>update('category','')}>All</button>{categories.map(category=><button key={category} className={filters.category===category?'active':''} onClick={()=>update('category',category)}>{category}</button>)}</div></div><div className="catalogue-sections">{groups.map(g=><ProductRail key={g.category} {...g} onDetails={setDetails}/>)}{!groups.length&&<div className="empty"><Package size={35}/><h3>{products.length?'No matching products':'Your catalogue is empty'}</h3><p>{products.length?'Try another search or category.':'Add products to your business catalogue first.'}</p></div>}</div>{status&&<div className="catalogue-status" role="status">{status}</div>}{details&&<div className="product-sheet-backdrop" onClick={()=>!busy&&setDetails(null)}><section className="product-detail-sheet" role="dialog" aria-modal="true" aria-label={`${details.name} details`} onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" aria-label="Close product details" onClick={()=>setDetails(null)}><X size={20}/></button><div className="product-sheet-hero"><ProductImage product={productSnapshot(details)}/><div><span className={`stock-badge ${productSnapshot(details).availability}`}>{availabilityLabel(productSnapshot(details).availability)}</span><h2>{details.name}</h2><Price product={productSnapshot(details)}/></div></div><dl>{[['Category',details.category],['Composition / strength',[details.composition,details.strength].filter(Boolean).join(' · ')],['Brand',details.brand],['Form',details.form_type],['Pack size',details.pack_size]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not specified'}</dd></div>)}</dl>{(details.notes||details.description)&&<div className="product-sheet-notes"><h4>Details</h4><p>{details.notes||details.description}</p></div>}<button className="primary product-sheet-send" disabled={busy||!canSend} onClick={()=>send(details.id)}><Send size={17}/>{busy?'Sending…':'Send to chat'}</button></section></div>}</div></Dialog>}
