import type {Row} from './types';
export type ProductSnapshot={id:string;name:string;category:string;brand:string;composition:string;strength:string;form_type:string;pack_size:string;availability:string;image_url:string;notes:string};
export const categoryOrder=['Injection','Tablet','Ointment','Surgical','General / Consumables'];
export function productSnapshot(p:Row):ProductSnapshot{return {id:p.id,name:String(p.name||''),category:String(p.category||'General / Consumables'),brand:String(p.brand||''),composition:String(p.composition||''),strength:String(p.strength||''),form_type:String(p.form_type||''),pack_size:String(p.pack_size||''),availability:p.availability==='on_request'?'on_request':Number(p.stock)<=0?'out_of_stock':p.availability==='out_of_stock'?'out_of_stock':'in_stock',image_url:typeof p.image_url==='string'&&p.image_url.startsWith('https://')?p.image_url:'',notes:String(p.notes||p.description||'')};}
export const availabilityLabel=(value:string)=>({in_stock:'In stock',out_of_stock:'Out of stock',on_request:'On request'}[value]||'On request');
export type Filters={query:string;category:string;brand:string;form:string;stock:string;sort:string;featured:boolean};
export function catalogueGroups(products:Row[],f:Filters){const query=f.query.trim().toLowerCase();const items=products.filter(p=>{const s=productSnapshot(p);return (!query||[s.name,s.brand,s.composition,s.strength].join(' ').toLowerCase().includes(query))&&(!f.category||s.category===f.category)&&(!f.brand||s.brand===f.brand)&&(!f.form||s.form_type===f.form)&&(!f.stock||s.availability===f.stock)&&(!f.featured||p.featured)}).sort((a,b)=>f.sort==='newest'?String(b.created_at||'').localeCompare(String(a.created_at||'')):f.sort==='availability'?productSnapshot(a).availability.localeCompare(productSnapshot(b).availability)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));const categories=[...new Set(items.map(p=>productSnapshot(p).category))].sort((a,b)=>{const ai=categoryOrder.indexOf(a),bi=categoryOrder.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)||a.localeCompare(b)});return categories.map(category=>({category,products:items.filter(p=>productSnapshot(p).category===category)}));}
export function catalogueDemoProducts():Row[]{return [
['Ceftriaxone','Injection','Ceftriaxone','1 g','Vial'],['Pantoprazole','Injection','Pantoprazole','','Vial'],['Ondansetron','Injection','Ondansetron','','Ampoule'],['Diclofenac','Injection','Diclofenac','','Ampoule'],['Methylcobalamin','Injection','Methylcobalamin','','Ampoule'],
['Pantoprazole tablets','Tablet','Pantoprazole','','Strip'],['Ofloxacin tablets','Tablet','Ofloxacin','','Strip'],['Levocetirizine tablets','Tablet','Levocetirizine','','Strip'],['DSR tablets','Tablet','','','Strip'],
['Povidone iodine ointment','Ointment','Povidone iodine','','Tube'],['Itraconazole ointment','Ointment','Itraconazole','','Tube'],
['IV set','Surgical','','','Single unit'],['Disposable syringe','Surgical','','','Single unit'],['Micropore tape','Surgical','','','Roll'],['Bandage','Surgical','','','Roll'],
['Cotton roll','General / Consumables','','','Roll'],['Normal saline','General / Consumables','Sodium chloride','','Bottle'],['Care essentials kit','General / Consumables','','','Kit']
].map((p,i)=>({id:`catalogue-demo-${i}`,name:p[0],category:p[1],composition:p[2],strength:p[3],pack_size:p[4],form_type:p[1]==='General / Consumables'?'Consumable':p[1],brand:'',stock:i%7===0?0:24+i,availability:i%6===0?'on_request':i%7===0?'out_of_stock':'in_stock',featured:i%5===0,image_url:'',notes:'Illustrative catalogue entry. Confirm manufacturer, composition, strength and pack details before live use.',description:'Sample product for catalogue browsing.',currency:'INR',price:0,retailer_id:'',catalogue_id:'',created_at:'2026-09-16T00:00:00Z'}));}
