import {catalogueDemoProducts,productSnapshot} from './catalogue';
import type {Action,Data,Message} from './types';
import {messagingOpen,normalizePhone,templateText} from './domain';
const uid=()=>crypto.randomUUID();
export function demoData():Data{
const now=Date.now(),stamp=(m:number)=>new Date(now-m*60000).toISOString();
const contacts=[['Dr. Arjun Mehta','Tarana Clinic','Doctor','Can you share the updated product catalogue?'],['MediPlus Pharmacy','MediPlus','Pharmacy','Thank you! We’ll confirm the quantities today.'],['Dr. Priya Sharma','City Care Clinic','Doctor','Please arrange a callback tomorrow morning.'],['Aarav Singh','Aarav Retail','Customer','Is delivery available in Ujjain?'],['HealthMate Supplies','HealthMate','Supplier','The new catalogue is ready.'],['City Care Diagnostics','City Care','Partner','Could you send the revised quotation?']].map((x,i)=>({id:`c${i}`,name:x[0],phone:`+91900000000${i}`,company:x[1],category:x[2],tags:[x[2],...(i===0?['High Priority']:[])],priority:i===0?'high':'normal',opted_in:i!==3,custom_fields:{},preview:x[3]}));
const conversations=contacts.map((c,i)=>({id:`v${i}`,contact_id:c.id,mode:(i===2?'human':i===4?'paused':'ai') as 'ai'|'human'|'paused',assigned_to:i===2?'priya':'me',unread:i===0?2:i===1?1:0,last_inbound_at:stamp(i===4?1800:10+i*24),updated_at:stamp(10+i*24),preview:c.preview,version:0}));
const messages:Message[]=conversations.flatMap((c,i)=>[{id:`m${i}a`,conversation_id:c.id,direction:'in',kind:'text',body:'Hello! I’d like to know more about your products and availability.',status:'received',created_at:stamp(65+i*24),sender_name:contacts[i].name},{id:`m${i}b`,conversation_id:c.id,direction:'out',kind:'text',body:'Hello! Welcome to our business. I can help with catalogue details, availability and delivery information.',status:'read',created_at:stamp(62+i*24),sender_name:'Open Chet AI'},{id:`m${i}c`,conversation_id:c.id,direction:'in',kind:'text',body:c.preview,status:'received',created_at:c.last_inbound_at!,sender_name:contacts[i].name}]);
return {organization_id:'demo',user_id:'me',role:'owner',contacts,conversations,messages,notes:[{id:'n1',conversation_id:'v0',body:'Prefers morning communication. Interested in the updated catalogue.',created_at:stamp(55),author_name:'Vishal'}],templates:[{id:'t1',name:'welcome_update',category:'UTILITY',language:'en',status:'DEMO',body:'Hello {{1}}, thank you for contacting us. How can we help you today?',variables:['name']},{id:'t2',name:'order_dispatched',category:'UTILITY',language:'en',status:'DEMO',body:'Hi {{1}}, your order {{2}} has been dispatched.',variables:['name','order']},{id:'t3',name:'catalogue_update',category:'MARKETING',language:'en',status:'DEMO',body:'Hello {{1}}, our updated catalogue is available. Reply to request a copy.',variables:['name']}],quick_replies:[{id:'q1',shortcut:'/welcome',body:'Hello! Thank you for reaching out. How can we help?'},{id:'q2',shortcut:'/catalogue',body:'Happy to share our latest catalogue. Which products are you interested in?'},{id:'q3',shortcut:'/location',body:'Our team is based in Tarana, Madhya Pradesh.'}],products:[...catalogueDemoProducts(),{id:'p1',name:'Everyday care kit',category:'Essentials',description:'A convenient collection of everyday care essentials.',price:450,currency:'INR',stock:24,retailer_id:'care-kit'},{id:'p2',name:'Digital thermometer',category:'Equipment',description:'Compact digital thermometer with a clear display.',price:199,currency:'INR',stock:48,retailer_id:'thermometer'}],campaigns:[],campaign_recipients:[],automation_rules:[],members:[{id:'me',name:'Vishal Parmar',role:'owner',status:'available'},{id:'priya',name:'Priya Sharma',role:'agent',status:'available'}],audit_logs:[],notifications:[],settings:{name:'Open Chet workspace',ai_enabled:true,auto_pause:true,tone:'Friendly',instructions:'Help with product enquiries and business information. Escalate clinical questions to a human. Never diagnose or prescribe.',blocked_topics:'diagnosis, prescriptions',business_hours:'09:00–19:00',timezone:'Asia/Kolkata',escalation_threshold:0.7},connection:{whatsapp:false,ai:false}};
}
export function demoAction(data:Data,action:Action):Data{
const d=structuredClone(data),v=action.values||{},id=action.id,now=new Date().toISOString();const c=d.conversations.find(c=>c.id===id);
const log=(body:string)=>d.audit_logs.unshift({id:uid(),conversation_id:id,body,created_at:now});
switch(action.type){
case 'mode':if(c){c.mode=v.mode;c.version++;if(v.mode==='human')c.assigned_to=d.user_id;log(`Conversation changed to ${v.mode}`)}break;
case 'read':if(c)c.unread=0;break;
case 'assign':if(c){c.assigned_to=v.assigned_to;log('Conversation assignment updated')}break;
case 'send':{if(!c)throw Error('Conversation not found');if(v.kind!=='template'&&!messagingOpen(c.last_inbound_at))throw Error('The messaging window has closed. Select a template.');if(d.settings.auto_pause){c.mode='human';c.version++}let body=v.body;let snapshot;if(v.kind==='product'){const p=d.products.find(p=>p.id===v.product_id);if(!p)throw Error('Product not found');snapshot=productSnapshot(p);body=snapshot.name;} if(v.kind==='template'){const t=d.templates.find(t=>t.id===v.template_id);if(!t)throw Error('Template missing');body=templateText(t.body,v.variables||[])}d.messages.push({id:uid(),conversation_id:c.id,direction:'out',kind:v.kind||'text',body,media_url:v.media_url,status:'demo',created_at:now,sender_name:'Vishal',...(snapshot?{product_snapshot:snapshot}:{})});c.preview=body;c.updated_at=now;break;}
case 'note':d.notes.push({id:uid(),conversation_id:id,body:v.body,created_at:now,author_name:'Vishal'});break;
case 'contact':{const phone=normalizePhone(v.phone);if(d.contacts.some(x=>x.phone===phone&&x.id!==id))throw Error('This phone number already exists.');if(id)Object.assign(d.contacts.find(x=>x.id===id)!,v,{phone});else d.contacts.push({id:uid(),name:v.name,company:'',category:'',tags:[],priority:'normal',opted_in:false,custom_fields:{},...v,phone});break;}
case 'open':{const found=d.conversations.find(x=>x.contact_id===id);if(!found)d.conversations.unshift({id:uid(),contact_id:id!,mode:'paused',version:0,assigned_to:'me',unread:0,last_inbound_at:null,updated_at:now,preview:'New conversation'});break;}
case 'settings':Object.assign(d.settings,v);break;
case 'quick_reply':case 'product':case 'automation':{const key=action.type==='quick_reply'?'quick_replies':action.type==='product'?'products':'automation_rules';if(id)Object.assign(d[key].find(x=>x.id===id)!,v);else d[key].push({id:uid(),...v});break;}
case 'campaign':d.campaigns.push({id:uid(),...v,status:'draft',created_at:now});break;
case 'campaign_start':{const campaign=d.campaigns.find(x=>x.id===id)!;campaign.status='demo_completed';const recipients=d.contacts.filter(x=>x.opted_in&&(!campaign.tag||x.tags.includes(campaign.tag))&&(!campaign.contact_ids?.length||campaign.contact_ids.includes(x.id)));recipients.forEach(x=>d.campaign_recipients.push({id:uid(),campaign_id:id,contact_id:x.id,status:'demo',created_at:now}));break;}
case 'notify_read':d.notifications=[];break;
case 'simulate':if(c){d.messages.push({id:uid(),conversation_id:c.id,direction:'in',body:v.body,kind:'text',status:'received',sender_name:d.contacts.find(x=>x.id===c.contact_id)!.name,created_at:now});c.last_inbound_at=now;c.updated_at=now;c.preview=v.body;c.unread++;d.notifications.unshift({id:uid(),body:'Demo incoming message',created_at:now});}break;
default:throw Error('Action unavailable in demo mode');
}return d;}
