import postgres from 'postgres';
import {createClient} from '@supabase/supabase-js';
import type {Role} from './types';
let pool:ReturnType<typeof postgres>|undefined;
export function db(){if(!process.env.DATABASE_URL)throw new HttpError(503,'Database connection is not configured.');return pool??=postgres(process.env.DATABASE_URL,{ssl:'require',prepare:false,max:4,connect_timeout:10,idle_timeout:20});}
export function adminDB(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export async function identity(req:Request){const token=req.headers.get('authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)throw new HttpError(401,'Sign in required');if(!process.env.NEXT_PUBLIC_SUPABASE_URL)throw new HttpError(503,'Supabase is not configured');const auth=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false}});const {data,error}=await auth.auth.getUser(token);if(error||!data.user)throw new HttpError(401,'Session expired');return data.user;}
export async function context(req:Request){const user=await identity(req);const requested=req.headers.get('x-organization-id');const rows=requested?await db()`select m.*,u.name from organization_members m join users u on u.id=m.user_id where m.user_id=${user.id} and m.organization_id=${requested}`:await db()`select m.*,u.name from organization_members m join users u on u.id=m.user_id where m.user_id=${user.id} order by m.created_at limit 1`;if(!rows.length)throw new HttpError(409,'Create your workspace first');return {org:rows[0].organization_id as string,user:user.id,name:rows[0].name as string,role:rows[0].role as Role};}
export function failure(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status});if(error instanceof Error&&error.name==='ZodError')return Response.json({error:'Please check the submitted fields.'},{status:400});const code=(error as {code?:string})?.code;if(code==='23505')return Response.json({error:'This record already exists.'},{status:409});if(code==='23503')return Response.json({error:'A referenced record does not belong to this workspace.'},{status:400});console.error('Open Chet request failed',error instanceof Error?error.name:'unknown');return Response.json({error:'The operation could not be completed. Check integration configuration and retry.'},{status:500});}
export async function body(req:Request){const raw=await req.text();if(raw.length>100_000)throw new HttpError(413,'Request too large');return JSON.parse(raw)}
