-- All client writes go through authenticated, role-checked application routes.
create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,settings jsonb not null default '{"ai_enabled":false,"auto_pause":true,"tone":"Professional","instructions":"Answer business questions only. Escalate uncertainty.","blocked_topics":"","business_hours":"09:00–19:00","timezone":"Asia/Kolkata","escalation_threshold":0.7}',created_at timestamptz not null default now());
create table public.users(id uuid primary key references auth.users(id) on delete cascade,name text not null default '',created_at timestamptz not null default now());
create table public.organization_members(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),user_id uuid not null references public.users(id),role text not null check(role in ('owner','admin','manager','agent')),status text not null default 'available',created_at timestamptz not null default now(),unique(organization_id,user_id));
create table public.whatsapp_accounts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),phone_number_id text not null unique,business_account_id text not null,created_at timestamptz not null default now());
create table public.contacts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,phone text not null check(phone ~ '^\+[1-9][0-9]{7,14}$'),company text not null default '',category text not null default '',priority text not null default 'normal',opted_in boolean not null default false,custom_fields jsonb not null default '{}',source text not null default 'manual',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,phone),unique(organization_id,id));
create table public.conversations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contact_id uuid not null,mode text not null default 'paused' check(mode in('ai','paused','human')),assigned_to uuid,version integer not null default 0,unread integer not null default 0 check(unread>=0),last_inbound_at timestamptz,preview text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,contact_id),foreign key(organization_id,contact_id) references public.contacts(organization_id,id),foreign key(organization_id,assigned_to) references public.organization_members(organization_id,user_id));
create table public.messages(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),conversation_id uuid not null,direction text not null check(direction in('in','out')),kind text not null default 'text',body text not null default '',status text not null default 'queued',sender_id uuid references public.users(id),sender_name text not null default '',meta_message_id text unique,media_id text,media_url text,payload jsonb not null default '{}',idempotency_key uuid unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,conversation_id) references public.conversations(organization_id,id));
create table public.message_status_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),meta_message_id text not null,status text not null,event_at timestamptz not null,error_code text,created_at timestamptz not null default now(),unique(meta_message_id,status,event_at));
create table public.conversation_assignments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),conversation_id uuid not null,user_id uuid,assigned_by uuid references public.users(id),created_at timestamptz not null default now(),foreign key(organization_id,conversation_id) references public.conversations(organization_id,id),foreign key(organization_id,user_id) references public.organization_members(organization_id,user_id));
create table public.tags(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,created_at timestamptz not null default now(),unique(organization_id,name),unique(organization_id,id));
create table public.contact_tags(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contact_id uuid not null,tag_id uuid not null,created_at timestamptz not null default now(),foreign key(organization_id,contact_id) references public.contacts(organization_id,id),foreign key(organization_id,tag_id) references public.tags(organization_id,id),unique(contact_id,tag_id));
create table public.notes(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),conversation_id uuid not null,body text not null,author_id uuid references public.users(id),author_name text not null default '',created_at timestamptz not null default now(),foreign key(organization_id,conversation_id) references public.conversations(organization_id,id));
create table public.templates(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),meta_id text,name text not null,category text not null,language text not null,status text not null default 'PENDING',body text not null default '',components jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,name,language),unique(organization_id,id));
create table public.quick_replies(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),shortcut text not null,body text not null,created_at timestamptz not null default now(),unique(organization_id,shortcut));
create table public.campaigns(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,template_id uuid not null,tag text not null default '',contact_ids jsonb not null default '[]',variables jsonb not null default '[]',scheduled_at timestamptz,status text not null default 'draft',created_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,template_id) references public.templates(organization_id,id));
create table public.campaign_recipients(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),campaign_id uuid not null,contact_id uuid not null,message_id uuid,status text not null default 'queued',created_at timestamptz not null default now(),foreign key(organization_id,campaign_id) references public.campaigns(organization_id,id),foreign key(organization_id,contact_id) references public.contacts(organization_id,id),foreign key(organization_id,message_id) references public.messages(organization_id,id),unique(campaign_id,contact_id));
create table public.products(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,description text not null default '',category text not null default '',price numeric(12,2) not null default 0 check(price>=0),currency text not null default 'INR',stock integer not null default 0,image_url text not null default '',retailer_id text not null default '',catalogue_id text not null default '',created_at timestamptz not null default now());
create table public.automation_rules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,trigger text not null check(trigger in ('keyword','new_contact','tag')),match text not null default '',action text not null check(action in('pause','tag','assign','reply')),value text not null default '',enabled boolean not null default true,created_at timestamptz not null default now());
create table public.ai_sessions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),conversation_id uuid not null,input_message_id uuid not null,status text not null default 'queued',expected_version integer not null,confidence numeric,error text,created_at timestamptz not null default now(),foreign key(organization_id,conversation_id) references public.conversations(organization_id,id),foreign key(organization_id,input_message_id) references public.messages(organization_id,id),unique(input_message_id));
create table public.audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),conversation_id uuid,actor_id uuid references public.users(id),body text not null,created_at timestamptz not null default now(),foreign key(organization_id,conversation_id) references public.conversations(organization_id,id));
create table public.notifications(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),body text not null,conversation_id uuid,created_at timestamptz not null default now(),foreign key(organization_id,conversation_id) references public.conversations(organization_id,id));
-- Private membership lookup avoids recursive RLS. No public callable definer.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;
create function private.member(org uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.organization_members m where m.organization_id=org and m.user_id=auth.uid()) $$;
revoke all on function private.member(uuid) from public;
grant execute on function private.member(uuid) to authenticated;
alter table public.organizations enable row level security;
create policy tenant_read on public.organizations for select to authenticated using(private.member(id));
grant select on public.organizations to authenticated;
alter table public.users enable row level security;
create policy self_read on public.users for select to authenticated using(id=(select auth.uid()));
grant select on public.users to authenticated;
do $$ declare t text; begin
foreach t in array array['organization_members','whatsapp_accounts','contacts','conversations','messages','message_status_events','conversation_assignments','tags','contact_tags','notes','templates','quick_replies','campaigns','campaign_recipients','products','automation_rules','ai_sessions','audit_logs','notifications'] loop
execute format('alter table public.%I enable row level security',t);
execute format('create policy tenant_read on public.%I for select to authenticated using (private.member(organization_id))',t);
execute format('grant select on public.%I to authenticated',t);
execute format('revoke insert,update,delete on public.%I from anon,authenticated',t);
execute format('create index on public.%I(organization_id,created_at desc)',t);
end loop;end $$;
create index on public.organization_members(user_id,organization_id);
create index on public.conversations(organization_id,updated_at desc,id);
create index on public.messages(organization_id,conversation_id,created_at desc,id);
create index on public.messages(status,created_at) where status='queued';
create index on public.ai_sessions(status,created_at) where status='queued';
create index on public.campaigns(status,scheduled_at);
create index on public.contact_tags(organization_id,contact_id);
-- Supabase hosts this publication. Local schema tests need not install Realtime.
do $$ begin if exists(select 1 from pg_publication where pubname='supabase_realtime') then alter publication supabase_realtime add table public.messages,public.conversations,public.notes,public.notifications;end if;end $$;
-- Private media bucket: only server routes upload/download after membership checks.
insert into storage.buckets(id,name,public,file_size_limit) values('open-chet-media','open-chet-media',false,16777216) on conflict(id) do nothing;
